"""Multi-head jammer presence, class, and power predictor."""

from __future__ import annotations

from typing import Any

import h5py
import torch
from torch import nn

from .training_utils import default_model_path, resolve_device


class JammerDetector(nn.Module):
    """Predict jammer presence, strategy class, and total jamming power."""

    def __init__(self, input_dim: int = 256, embedding_dim: int = 64, num_types: int = 5) -> None:
        super().__init__()
        self.encoder = nn.Sequential(nn.Linear(input_dim, embedding_dim), nn.ReLU(), nn.Linear(embedding_dim, embedding_dim), nn.ReLU())
        self.presence = nn.Linear(embedding_dim, 1)
        self.jammer_type = nn.Linear(embedding_dim, num_types)
        self.power = nn.Linear(embedding_dim, 1)

    def forward(self, state: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        embedding = self.encoder(state)
        return self.presence(embedding).squeeze(-1), self.jammer_type(embedding), self.power(embedding).squeeze(-1)


def train_detector(epochs: int = 100, device: str = "cpu",
                   training_config: dict[str, Any] | None = None,
                   teacher_path: str = "data/ground_truth/teacher_dataset.h5") -> JammerDetector:
    """Train detector heads using jamming labels generated by Step 3."""
    config = training_config or {}
    with h5py.File(teacher_path, "r") as source:
        states = torch.tensor(source["states"][()], dtype=torch.float32)
        jammer_power = torch.tensor(source["jammer_actions"][()].sum(axis=1), dtype=torch.float32)
    target_device = resolve_device(device)
    model = JammerDetector().to(target_device)
    optimizer = torch.optim.Adam(model.parameters(), lr=float(config.get("learning_rate", 1e-3)))
    states, jammer_power = states.to(target_device), jammer_power.to(target_device)
    presence = (jammer_power > 1e-8).float()
    jammer_type = torch.zeros(len(states), dtype=torch.long, device=target_device)
    for _ in range(epochs):
        presence_logits, type_logits, predicted_power = model(states)
        loss = (nn.functional.binary_cross_entropy_with_logits(presence_logits, presence)
                + nn.functional.cross_entropy(type_logits, jammer_type)
                + nn.functional.mse_loss(predicted_power, jammer_power))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    model.eval()
    torch.save({"state_dict": model.state_dict()}, default_model_path("jammer_detector"))
    return model